CREATE TABLE USUARIOS(
ID_USUARIO INT IDENTITY (1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
TIPO_USR VARCHAR(50) NOT NULL,
NACIMIENTO VARCHAR(50) NOT NULL,
CONTRASEÑA VARCHAR(50) NOT NULL
)