CREATE TABLE USUARIO (
ID_USUARIO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
TIPO_USR VARCHAR(50) NOT NULL,
NACIMIENTO DATE NOT NULL,
CONTASEÑA VARCHAR(50) NOT NULL
)