CREATE TABLE USUARIO(
ID_USUARIOS INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
TIPO_USR VARCHAR(50) NOT NULL,
NACIMIENTO VARCHAR(50) NOT NULL,
CONTRASEÑA VARCHAR(50) NOT NULL
)

CREATE TABLE EDITORIAS(
ID_EDITORIAS INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(50) NOT NULL
)

CREATE TABLE GENERO(
ID_GENERO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE LIBROS(
ID_LIBROS INT IDENTITY (1,1) PRIMARY KEY,
TITULO VARCHAR(50) NOT NULL,
AUTOR VARCHAR(50) NOT NULL,
CANTIDAD VARCHAR(50)  NOT NULL
CONSTRAINT fk_EDITORIAS FOREIGN KEY (ID_LIBROS) REFERENCES EDITORIAS(ID_EDITORIAS),
CONSTRAINT fk_GENERO FOREIGN KEY (ID_LIBROS) REFERENCES GENERO(ID_GENERO)
)

CREATE TABLE PRESTAMO(
ID_PRESTAMO INT IDENTITY (1,1) PRIMARY KEY,
ESTATUS VARCHAR(50) NOT NULL,
CONSTRAINT fk_USUARIO FOREIGN KEY (ID_PRESTAMO) REFERENCES USUARIO(ID_USUARIO),
CONSTRAINT fk_LIBRO FOREIGN KEY (ID_PRESTAMO) REFERENCES LIBRO(ID_LIBRO)
)

CREATE TABLE BITACORAS(
ID_BITACORA  INT IDENTITY (1,1) PRIMARY KEY,
FECHA VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
DIRECCION_IP VARCHAR(50) NOT NULL,
ACCION VARCHAR(254) NOT NULL
)

INSERT INTO BITACORAS(FECHA,USUARIO,DIRECCION_IP,ACCION) VALUES ('01/02/2021','JUANP','2800:98:1127:534:1e9:6a2c:6731:1ae2','LOGIN')

SELECT * FROM BITACORAS

INSERT INTO USUARIO(NOMBRE,APELLIDO,USUARIO,TIPO_USR,NACIMIENTO,CONTASEÑA) VALUES ('JUANA','MARTINEZ','CLIENTE','19/08/1995','JUANAMARTINEZ')

SELECT * FROM USUARIO

CREATE TABLE ENCRIPTADOS(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nombre1 VarChar(20),
Nombre2 NVarchar(20),
NClave1 VarBinary(8000),
NClave2 VarBinary(8000)
)
GO
Declare @cf Nvarchar(200);
set @cf = N'Esta es la clave de cifrado';
 
INSERT INTO ENCRIPTADOS(
Nombre1,
Nombre2,
NClave1,
NClave2
)

values(
'PruEbA1',
'NPruEbA1',
ENCRYPTBYPASSPHRASE(@cf,'PruEbA1'),
ENCRYPTBYPASSPHRASE(@cf,N'PruEbA1')
)

(SELECT CAST(GETUTCDATE() AS VARCHAR(20)))
(SELECT CAST(GETUTCDATE() AS NVARCHAR(20))),
ENCRYPTBYPASSPHRASE(@cf),
(SELECT CAST(GETUTCDATE() AS VARCHAR(20)))),
ENCRYPTBYPASSPHRASE(@cf),
(SELECT CAST(GETUTCDATE() AS NVARCHAR(20))));

SELECT Id
     , Nombre1
     , Nombre2
     , NClave1
     , NClave2
FROM ENCRIPTADOS;

update USUARIO set CONTRASEÑA = 'JUANPEREZ' where ID_USUARIO = 1
update USUARIO set CONTRASEÑA = ENCRYPTBYPASSPHRASE('ENCRIPTACION','JUANPEREZ') WHERE ID_USUARIO = 1


SELECT * FROM USUARIO

INSERT INTO USUARIO(NOMBRE,APELLIDO,USUARIO,TIPO_USR,NACIMIENTO,CONTRASEÑA) VALUES ('ADMIN','ADMIN','ADMIN','ADMIN','10/10/2021','ADMIN')
INSERT INTO USUARIO(NOMBRE,APELLIDO,USUARIO,TIPO_USR,NACIMIENTO,CONTRASEÑA) VALUES ('CLIENTE','CLIENTE','CLIENTE','CLIENTE','10/10/2021','CLIENTE')

SELECT ENCRYPTBYPASSPHRASE ('PRUEBA','123')

SELECT DECRYPTBYPASSPHRASE ('PRUEBA', 0x020000008EE70DC7FF3E032E1368C073283D1BF42D9E2255D11C7D7C45F0ED5599B7039E)